name = "meownote"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "meownote-db"
database_id = "a54a0c11-0e57-4ea8-abc1-5e04885759d0"   # 替换成你的 D1 database_id

